complete runtime error occur at int + string
garry911128/mini-python pull request #25
Opened 2024-12-16 14:00 UTC by garry911128

2024-12-16 16:01 UTC, kyynk requested changes
![image](https://github.com/user-attachments/assets/0bf88084-c777-4c5d-a4fc-065d9217b5f1)

2024-12-16 16:01 UTC, kyynk commented on mini-python-ocaml/compile.ml
> +  text_code, data_code
```suggestion
let create_runtime_error () : X86_64.text * X86_64.data =
  let error_label = "runtime_error" in
  let error_message = "Runtime error occurred\n" in
  let text_code =
    label error_label ++
    (* Prologue *)
    pushq (reg rbp) ++
    movq (reg rsp) (reg rbp) ++
    (* Load the error message *)
    leaq (lab "runtime_error_msg") rdi ++
    (* Call printf to print the error message *)
    xorq (reg rax) (reg rax) ++
    call "printf" ++
    (* Exit with a non-zero status *)
    movq (imm 1) (reg rdi) ++
    call "exit" ++
    (* No need for epilogue as the process will exit *)
    nop
  in
  let data_code =
    (* Data section for the error message *)
    label "runtime_error_msg" ++
    string error_message
  in
  text_code, data_code
```

2024-12-17 05:21 UTC, garry911128 commented on mini-python-ocaml/compile.ml
> +  text_code, data_code
fixed

2024-12-17 05:31 UTC, Vghxv approved these changes
LGTM

2024-12-17 06:06 UTC, kyynk approved these changes
LGTM

2024-12-17 06:06 UTC, merged