complete error type of `len` function
garry911128/mini-python pull request #32
Opened 2024-12-20 10:56 UTC by garry911128

Compilation:
Compilation: 22/48 : 45%
Code behavior: 22/48 : 45%
Expected output: 18/48 : 37%

2024-12-20 14:40 UTC, kyynk requested changes

2024-12-20 14:40 UTC, kyynk commented on mini-python-ocaml/compile.ml
> +        failwith "Unsupported function call"
```suggestion
  | TEcall (fn, args) ->
    if fn.fn_name = "len" then
      match args with
      | [e] ->
        let _, _, arg_type = compile_expr env e in
        begin match arg_type with
        | `string | `list -> (* 正確的類型 *)
          (* len 的實現邏輯 *)
          failwith "Implement len logic here"
        | `int ->
          call "runtime_error", nop, `int
        | _ -> (* 錯誤類型 *)
          failwith "TypeError: object of type is not iterable"
        end
      | _ ->
        failwith "TypeError: len() takes exactly one argument"
    else
      failwith "Unsupported function call"
```

2024-12-20 15:21 UTC, Vghxv commented
remove Chinese comments

2024-12-20 15:41 UTC, Vghxv commented
and please stop merging main into another branch next time, use rebase instead

2024-12-21 06:25 UTC, Vghxv approved these changes
LGTM

2024-12-21 06:25 UTC, Vghxv commented on mini-python-ocaml/test.py
> +print("make" + "love")
again then I quit

2024-12-21 06:25 UTC, Vghxv commented on mini-python-ocaml/compile.ml
> +
didn't consider len and tag of concatenated string
btw I did this

2024-12-21 06:38 UTC, kyynk approved these changes
LGTM

2024-12-21 06:38 UTC, merged