Com
garry911128/mini-python pull request #44
Opened 2024-12-23 11:19 UTC by Vghxv

Fix #37 
Fix #43

2024-12-23 12:49 UTC, garry911128 approved these changes

2024-12-23 13:22 UTC, kyynk requested changes
- will print last assign value
- does not print first iterate value
---
![image](https://github.com/user-attachments/assets/b2cecf24-ce8f-4868-a532-94745b444f9f)
---
![image](https://github.com/user-attachments/assets/96d2767c-dcae-4bd5-bef0-064e376fa72f)

2024-12-24 10:42 UTC, Vghxv commented
> * will print last assign value
this is desired behavior

> * does not print first iterate value
fixed

2024-12-24 12:01 UTC, kyynk approved these changes
LGTM

2024-12-24 12:02 UTC, merged